# Aplicação de Rank Rating
execute in minecraft:overworld run execute if score @p[distance=..8] rr matches 0 run team join rank_madeira @p[distance=..8]
execute in minecraft:overworld run execute if score @p[distance=..8] rr matches 3 run team join rank_pedra @p[distance=..8]
execute in minecraft:overworld run execute if score @p[distance=..8] rr matches 6 run team join rank_carvao @p[distance=..8]
execute in minecraft:overworld run execute if score @p[distance=..8] rr matches 9 run team join rank_cobre @p[distance=..8]
execute in minecraft:overworld run execute if score @p[distance=..8] rr matches 12 run team join rank_quartz @p[distance=..8]
execute in minecraft:overworld run execute if score @p[distance=..8] rr matches 15 run team join rank_ferro @p[distance=..8]
execute in minecraft:overworld run execute if score @p[distance=..8] rr matches 18 run team join rank_amethyst @p[distance=..8]
execute in minecraft:overworld run execute if score @p[distance=..8] rr matches 21 run team join rank_ouro @p[distance=..8]
execute in minecraft:overworld run execute if score @p[distance=..8] rr matches 24 run team join rank_redstone @p[distance=..8]
execute in minecraft:overworld run execute if score @p[distance=..8] rr matches 27 run team join rank_lazuli @p[distance=..8]
execute in minecraft:overworld run execute if score @p[distance=..8] rr matches 30 run team join rank_emerald @p[distance=..8]
execute in minecraft:overworld run execute if score @p[distance=..8] rr matches 33 run team join rank_diamond @p[distance=..8]
execute in minecraft:overworld run execute if score @p[distance=..8] rr matches 36 run team join rank_netherite @p[distance=..8]
execute in minecraft:overworld run execute if score @p[distance=..8] rr matches 39 run team join rank_drg @p[distance=..8]