# villagers.mcfunction | arame:villagers
# During the Start the of Game, this function will respawn All "Trading Villagers"

# Blue Side - Villagers
summon villager -88.5 146 -10.5 \
{VillagerData:{type:snow,profession:weaponsmith,level:4},Offers:{Recipes:[{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:8},sell:{id:cobblestone,Count:2}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:16},sell:{id:iron_ingot,Count:2}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:32},sell:{id:gold_ingot,Count:2}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:48},sell:{id:diamond,Count:2}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:64},sell:{id:netherite_ingot,Count:2}}]},CustomName:'[{"text":"Ferreiro"}]',Invulnerable:1b,NoAI:1b,OnGround:1b}
summon villager -93.5 146 -3.5 \
{VillagerData:{type:taiga,profession:fletcher,level:4},Offers:{Recipes:[{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:8},sell:{id:wooden_sword,Count:1,tag:{Unbreakable:1}}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:24},sell:{id:wooden_axe,Count:1,tag:{Unbreakable:1}}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:24},sell:{id:bow,Count:1,tag:{Unbreakable:1}}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:24},sell:{id:crossbow,Count:1,tag:{Unbreakable:1}}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:1},sell:{id:arrow,Count:12}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:32},sell:{id:shield,Count:1,tag:{Unbreakable:1}}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald_block,Count:16},buyB:{id:emerald,Count:24},sell:{id:trident,Count:1}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald_block,Count:32},buyB:{id:emerald,Count:64},sell:{id:totem_of_undying,Count:1}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:4},sell:{id:spyglass,Count:1}}]},CustomName:'[{"text":"Ferramenteiro"}]',Invulnerable:1b,NoAI:1b,OnGround:1b}
summon villager -84.5 146 -16.5 \
{VillagerData:{type:desert,profession:farmer,level:4},Offers:{Recipes:[{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:1},sell:{id:sweet_berries,Count:12}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:2},sell:{id:apple,Count:3}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:6},sell:{id:baked_potato,Count:3}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:6},sell:{id:cooked_cod,Count:3}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:12},sell:{id:cooked_porkchop,Count:6}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:12},sell:{id:cooked_beef,Count:6}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:24},sell:{id:golden_carrot,Count:6}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:32},sell:{id:honey_bottle,Count:8}}]},CustomName:'[{"text":"Fazendeiro"}]',Invulnerable:1b,NoAI:1b,OnGround:1b}
summon villager -93.5 143 14.5 \
{VillagerData:{type:swamp,profession:librarian,level:4},Offers:{Recipes:[{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:3},sell:{id:experience_bottle,Count:24}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:6},sell:{id:lapis_lazuli,Count:36}}]},CustomName:'[{"text":"Feitiçeiro"}]'}
summon villager -79.5 144 27.5 \
{VillagerData:{type:savanna,profession:cleric,level:4},Offers:{Recipes:[{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:24},sell:{id:dandelion,Count:1,tag:{display:{Name:'[{"text":"Dente de Leão","italic":false,"color":"yellow"}]',Lore:['[{"text":"ⓘ Efeito:","italic":false}]','[{"text":"- Velocidade","italic":false}]']}}}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:24},sell:{id:poppy,Count:1,tag:{display:{Name:'[{"text":"Rosa","italic":false,"color":"red"}]',Lore:['[{"text":"ⓘ Efeito:","italic":false}]','[{"text":"- Força","italic":false}]']}}}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:24},sell:{id:cornflower,Count:1,tag:{display:{Name:'[{"text":"Centáurea","italic":false,"color":"blue"}]',Lore:['[{"text":"ⓘ Efeito:","italic":false}]','[{"text":"- Impulsionador de Vida","italic":false}]']}}}},{maxUses:999,priceMultiplier:0,demand:-20,specialPrice:0,buy:{id:emerald,Count:24},sell:{id:allium,Count:1,tag:{display:{Name:'[{"text":"Flor d\'Alho","italic":false,"color":"dark_purple"}]',Lore:['[{"text":"ⓘ Efeito:","italic":false}]','[{"text":"- Velocidade de Ataque","italic":false}]']}}}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:24},sell:{id:white_tulip,Count:1,tag:{display:{Name:'[{"text":"Tulipa Branca","italic":false,"color":"white"}]',Lore:['[{"text":"ⓘ Efeito:","italic":false}]','[{"text":"- Regeneração","italic":false}]']}}}},{maxUses:999,priceMultiplier:0,specialPrice:0,buy:{id:emerald,Count:24},sell:{id:torchflower,Count:1,tag:{display:{Name:'[{"text":"Flor-Tocha","italic":false,"color":"gold"}]',Lore:['[{"text":"ⓘ Efeito:","italic":false}]','[{"text":"- Visão Noturna","italic":false}]']}}}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:24},sell:{id:red_mushroom,Count:1,tag:{display:{Name:'[{"text":"Cogumelo","italic":false,"color":"gray"}]',Lore:['[{"text":"ⓘ Efeito:","italic":false}]','[{"text":"- Resistência","italic":false}]']}}}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:24},sell:{id:wither_rose,Count:1,tag:{display:{Name:'[{"text":"Rosa do Wither","italic":false,"color":"dark_gray"}]',Lore:['[{"text":"ⓘ Efeito:","italic":false}]','[{"text":"- Jump Boost","italic":false}]']}}}}]},CustomName:'[{"text":"Cigano"}]'}

# Red Side - Villagers
summon villager 93.5 146 21.5 \
{VillagerData:{type:snow,profession:weaponsmith,level:4},Offers:{Recipes:[{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:8},sell:{id:cobblestone,Count:2}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:16},sell:{id:iron_ingot,Count:2}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:32},sell:{id:gold_ingot,Count:2}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:48},sell:{id:diamond,Count:2}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:64},sell:{id:netherite_ingot,Count:2}}]},CustomName:'[{"text":"Ferreiro"}]',Invulnerable:1b,NoAI:1b,OnGround:1b}
summon villager 98.5 146 14.5 \
{VillagerData:{type:taiga,profession:fletcher,level:4},Offers:{Recipes:[{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:8},sell:{id:wooden_sword,Count:1,tag:{Unbreakable:1}}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:24},sell:{id:wooden_axe,Count:1,tag:{Unbreakable:1}}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:24},sell:{id:bow,Count:1,tag:{Unbreakable:1}}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:24},sell:{id:crossbow,Count:1,tag:{Unbreakable:1}}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:1},sell:{id:arrow,Count:12}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:32},sell:{id:shield,Count:1,tag:{Unbreakable:1}}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald_block,Count:16},buyB:{id:emerald,Count:24},sell:{id:trident,Count:1}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald_block,Count:32},buyB:{id:emerald,Count:64},sell:{id:totem_of_undying,Count:1}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:4},sell:{id:spyglass,Count:1}}]},CustomName:'[{"text":"Ferramenteiro"}]',Invulnerable:1b,NoAI:1b,OnGround:1b}
summon villager 89.5 146 27.5 \
{VillagerData:{type:desert,profession:farmer,level:4},Offers:{Recipes:[{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:1},sell:{id:sweet_berries,Count:12}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:2},sell:{id:apple,Count:3}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:6},sell:{id:baked_potato,Count:3}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:6},sell:{id:cooked_cod,Count:3}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:12},sell:{id:cooked_porkchop,Count:6}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:12},sell:{id:cooked_beef,Count:6}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:24},sell:{id:golden_carrot,Count:6}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:32},sell:{id:honey_bottle,Count:8}}]},CustomName:'[{"text":"Fazendeiro"}]',Invulnerable:1b,NoAI:1b,OnGround:1b}
summon villager 98.5 143 -3.5 \
{VillagerData:{type:swamp,profession:librarian,level:4},Offers:{Recipes:[{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:3},sell:{id:experience_bottle,Count:24}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:6},sell:{id:lapis_lazuli,Count:36}}]},CustomName:'[{"text":"Feitiçeiro"}]'}
summon villager 84.5 144 -16.5 \
{VillagerData:{type:savanna,profession:cleric,level:4},Offers:{Recipes:[{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:24},sell:{id:dandelion,Count:1,tag:{display:{Name:'[{"text":"Dente de Leão","italic":false,"color":"yellow"}]',Lore:['[{"text":"ⓘ Efeito:","italic":false}]','[{"text":"- Velocidade","italic":false}]']}}}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:24},sell:{id:poppy,Count:1,tag:{display:{Name:'[{"text":"Rosa","italic":false,"color":"red"}]',Lore:['[{"text":"ⓘ Efeito:","italic":false}]','[{"text":"- Força","italic":false}]']}}}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:24},sell:{id:cornflower,Count:1,tag:{display:{Name:'[{"text":"Centáurea","italic":false,"color":"blue"}]',Lore:['[{"text":"ⓘ Efeito:","italic":false}]','[{"text":"- Impulsionador de Vida","italic":false}]']}}}},{maxUses:999,priceMultiplier:0,demand:-20,specialPrice:0,buy:{id:emerald,Count:24},sell:{id:allium,Count:1,tag:{display:{Name:'[{"text":"Flor d\'Alho","italic":false,"color":"dark_purple"}]',Lore:['[{"text":"ⓘ Efeito:","italic":false}]','[{"text":"- Velocidade de Ataque","italic":false}]']}}}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:24},sell:{id:white_tulip,Count:1,tag:{display:{Name:'[{"text":"Tulipa Branca","italic":false,"color":"white"}]',Lore:['[{"text":"ⓘ Efeito:","italic":false}]','[{"text":"- Regeneração","italic":false}]']}}}},{maxUses:999,priceMultiplier:0,specialPrice:0,buy:{id:emerald,Count:24},sell:{id:torchflower,Count:1,tag:{display:{Name:'[{"text":"Flor-Tocha","italic":false,"color":"gold"}]',Lore:['[{"text":"ⓘ Efeito:","italic":false}]','[{"text":"- Visão Noturna","italic":false}]']}}}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:24},sell:{id:red_mushroom,Count:1,tag:{display:{Name:'[{"text":"Cogumelo","italic":false,"color":"gray"}]',Lore:['[{"text":"ⓘ Efeito:","italic":false}]','[{"text":"- Resistência","italic":false}]']}}}},{maxUses:999,priceMultiplier:0,demand:0,specialPrice:0,buy:{id:emerald,Count:24},sell:{id:wither_rose,Count:1,tag:{display:{Name:'[{"text":"Rosa do Wither","italic":false,"color":"dark_gray"}]',Lore:['[{"text":"ⓘ Efeito:","italic":false}]','[{"text":"- Jump Boost","italic":false}]']}}}}]},CustomName:'[{"text":"Cigano"}]'}


# NPC AREA (VILLAGERS AND HORSES):

# Blue Side - Horses
summon horse -77.5 146 -21.5 {SaddleItem:{id:saddle,Count:1},Tame:1,CustomName:'[{"text":"Vacalo"}]'}
summon horse -77.5 146 -21.5 {SaddleItem:{id:saddle,Count:1},Tame:1,CustomName:'[{"text":"Vacalo"}]'}
summon horse -77.5 146 -21.5 {SaddleItem:{id:saddle,Count:1},Tame:1,CustomName:'[{"text":"Vacalo"}]'}

# Red Side - Horses
summon horse 82.5 146 32.5 {SaddleItem:{id:saddle,Count:1},Tame:1,CustomName:'[{"text":"Vacalo"}]'}
summon horse 82.5 146 32.5 {SaddleItem:{id:saddle,Count:1},Tame:1,CustomName:'[{"text":"Vacalo"}]'}
summon horse 82.5 146 32.5 {SaddleItem:{id:saddle,Count:1},Tame:1,CustomName:'[{"text":"Vacalo"}]'}