execute store result score @p random run random roll 1..30
execute if score @p random matches 1 run give @p compass{LodestoneTracked:0,LodestoneDimension:"minecraft:the_end",LodestonePos:{X:-13, Y:114, Z:-32},display:{Name:'[{"text":"Administração:","italic":false,"color":"green","bold":true},{"text":" Passar o Cartão","bold":false}]'}}
execute if score @p random matches 2 run give @p compass{LodestoneTracked:0,LodestoneDimension:"minecraft:the_end",LodestonePos:{X:-14, Y:114, Z:-57},display:{Name:'[{"text":"Cafetaria:","italic":false,"color":"green","bold":true},{"text":" Limpar a Ventilação","bold":false}]'}}
execute if score @p random matches 3 run give @p compass{LodestoneTracked:0,LodestoneDimension:"minecraft:the_end",LodestonePos:{X:-12, Y:114, Z:-66},display:{Name:'[{"text":"Cafetaria:","italic":false,"color":"green","bold":true},{"text":" Pegar o Lixo","bold":false}]'}}
execute if score @p random matches 4 run give @p compass{LodestoneTracked:0,LodestoneDimension:"minecraft:the_end",LodestonePos:{X:-15, Y:114, Z:-71},display:{Name:'[{"text":"Cafetaria:","italic":false,"color":"green","bold":true},{"text":" Levantar Dados","bold":false}]'}}
execute if score @p random matches 5 run give @p compass{LodestoneTracked:0,LodestoneDimension:"minecraft:the_end",LodestonePos:{X:-11, Y:114, Z:-20},display:{Name:'[{"text":"Comunicações:","italic":false,"color":"green","bold":true},{"text":" Desviar Eletrecidade","bold":false}]'}}
execute if score @p random matches 6 run give @p compass{LodestoneTracked:0,LodestoneDimension:"minecraft:the_end",LodestonePos:{X:-16, Y:114, Z:-20},display:{Name:'[{"text":"Comunicações:","italic":false,"color":"green","bold":true},{"text":" Levantar Dados","bold":false}]'}}
execute if score @p random matches 7 run give @p compass{LodestoneTracked:0,LodestoneDimension:"minecraft:the_end",LodestonePos:{X:-42, Y:114, Z:-38},display:{Name:'[{"text":"Elétrica:","italic":false,"color":"green","bold":true},{"text":" Calibrar Distribuidor","bold":false}]'}}
execute if score @p random matches 8 run give @p compass{LodestoneTracked:0,LodestoneDimension:"minecraft:the_end",LodestonePos:{X:-46, Y:114, Z:-38},display:{Name:'[{"text":"Elétrica:","italic":false,"color":"green","bold":true},{"text":" Arranjar Fios","bold":false}]'}}
execute if score @p random matches 9 run give @p compass{LodestoneTracked:0,LodestoneDimension:"minecraft:the_end",LodestonePos:{X:-49, Y:114, Z:-38},display:{Name:'[{"text":"Elétrica:","italic":false,"color":"green","bold":true},{"text":" Levantar Dados","bold":false}]'}}
execute if score @p random matches 10 run give @p compass{LodestoneTracked:0,LodestoneDimension:"minecraft:the_end",LodestonePos:{X:-72, Y:114, Z:-55},display:{Name:'[{"text":"Motor Superior:","italic":false,"color":"green","bold":true},{"text":" Alinhar Motor","bold":false}]'}}
execute if score @p random matches 11 run give @p compass{LodestoneTracked:0,LodestoneDimension:"minecraft:the_end",LodestonePos:{X:-61, Y:114, Z:-36},display:{Name:'[{"text":"Motor Inferior:","italic":false,"color":"green","bold":true},{"text":" Desviar Eletrecidade","bold":false}]'}}
execute if score @p random matches 12 run give @p compass{LodestoneTracked:0,LodestoneDimension:"minecraft:the_end",LodestonePos:{X:-61, Y:114, Z:-66},display:{Name:'[{"text":"Motor Superior:","italic":false,"color":"green","bold":true},{"text":" Desviar Eletrecidade","bold":false}]'}}
execute if score @p random matches 13 run give @p compass{LodestoneTracked:0,LodestoneDimension:"minecraft:the_end",LodestonePos:{X:-42, Y:114, Z:-48},display:{Name:'[{"text":"Enfermaria:","italic":false,"color":"green","bold":true},{"text":" Inspecionar Amostras","bold":false}]'}}
execute if score @p random matches 14 run give @p compass{LodestoneTracked:0,LodestoneDimension:"minecraft:the_end",LodestonePos:{X:-44, Y:114, Z:-44},display:{Name:'[{"text":"Enfermaria:","italic":false,"color":"green","bold":true},{"text":" Submeter um Escaneamento","bold":false}]'}}
execute if score @p random matches 15 run give @p compass{LodestoneTracked:0,LodestoneDimension:"minecraft:the_end",LodestonePos:{X:18, Y:114, Z:-46},display:{Name:'[{"text":"Navegação:","italic":false,"color":"green","bold":true},{"text":" Cursar Rota","bold":false}]'}}
execute if score @p random matches 16 run give @p compass{LodestoneTracked:0,LodestoneDimension:"minecraft:the_end",LodestonePos:{X:13, Y:114, Z:-49},display:{Name:'[{"text":"Navegação:","italic":false,"color":"green","bold":true},{"text":" Desviar Eletrecidade","bold":false}]'}}
execute if score @p random matches 17 run give @p compass{LodestoneTracked:0,LodestoneDimension:"minecraft:the_end",LodestonePos:{X:20, Y:114, Z:-43},display:{Name:'[{"text":"Navegação:","italic":false,"color":"green","bold":true},{"text":" Estabilizar Direção","bold":false}]'}}
execute if score @p random matches 18 run give @p compass{LodestoneTracked:0,LodestoneDimension:"minecraft:the_end",LodestonePos:{X:16, Y:114, Z:-49},display:{Name:'[{"text":"Navegação:","italic":false,"color":"green","bold":true},{"text":" Levantar Dados","bold":false}]'}}
execute if score @p random matches 19 run give @p compass{LodestoneTracked:0,LodestoneDimension:"minecraft:the_end",LodestonePos:{X:11, Y:114, Z:-49},display:{Name:'[{"text":"Oxigénio:","italic":false,"color":"green","bold":true},{"text":" Limpar Filtro","bold":false}]'}}
execute if score @p random matches 20 run give @p compass{LodestoneTracked:0,LodestoneDimension:"minecraft:the_end",LodestonePos:{X:-4, Y:114, Z:-49},display:{Name:'[{"text":"Oxigénio:","italic":false,"color":"green","bold":true},{"text":" Desviar Eletrecidade","bold":false}]'}}
execute if score @p random matches 21 run give @p compass{LodestoneTracked:0,LodestoneDimension:"minecraft:the_end",LodestonePos:{X:-13, Y:114, Z:-47},display:{Name:'[{"text":"Oxigénio:","italic":false,"color":"green","bold":true},{"text":" Pegar o Lixo","bold":false}]'}}
execute if score @p random matches 22 run give @p compass{LodestoneTracked:0,LodestoneDimension:"minecraft:the_end",LodestonePos:{X:-80, Y:114, Z:-45},display:{Name:'[{"text":"Reator:","italic":false,"color":"green","bold":true},{"text":" Iniciar Reator","bold":false}]'}}
execute if score @p random matches 23 run give @p compass{LodestoneTracked:0,LodestoneDimension:"minecraft:the_end",LodestonePos:{X:-81, Y:114, Z:-52},display:{Name:'[{"text":"Reator:","italic":false,"color":"green","bold":true},{"text":" Desbloquear Coletores","bold":false}]'}}
execute if score @p random matches 24 run give @p compass{LodestoneTracked:0,LodestoneDimension:"minecraft:the_end",LodestonePos:{X:-56, Y:114, Z:-48},display:{Name:'[{"text":"Segurança:","italic":false,"color":"green","bold":true},{"text":" Desviar Eletrecidade","bold":false}]'}}
execute if score @p random matches 25 run give @p compass{LodestoneTracked:0,LodestoneDimension:"minecraft:the_end",LodestonePos:{X:4, Y:114, Z:-29},display:{Name:'[{"text":"Escudos:","italic":false,"color":"green","bold":true},{"text":" Desviar Eletrecidade","bold":false}]'}}
execute if score @p random matches 26 run give @p compass{LodestoneTracked:0,LodestoneDimension:"minecraft:the_end",LodestonePos:{X:-6, Y:114, Z:-18},display:{Name:'[{"text":"Escudos:","italic":false,"color":"green","bold":true},{"text":" Ativar Escudos","bold":false}]'}}
execute if score @p random matches 27 run give @p compass{LodestoneTracked:0,LodestoneDimension:"minecraft:the_end",LodestonePos:{X:-32, Y:114, Z:-21},display:{Name:'[{"text":"Armazenamento:","italic":false,"color":"green","bold":true},{"text":" Inserir Combústivel nos Motores","bold":false}]'}}
execute if score @p random matches 28 run give @p compass{LodestoneTracked:0,LodestoneDimension:"minecraft:the_end",LodestonePos:{X:-1, Y:114, Z:-60},display:{Name:'[{"text":"Armas:","italic":false,"color":"green","bold":true},{"text":" Destruir Asteroides","bold":false}]'}}
execute if score @p random matches 29 run give @p compass{LodestoneTracked:0,LodestoneDimension:"minecraft:the_end",LodestonePos:{X:4, Y:114, Z:-60},display:{Name:'[{"text":"Armas:","italic":false,"color":"green","bold":true},{"text":" Desviar Eletrecidade","bold":false}]'}}
execute if score @p random matches 30 run give @p compass{LodestoneTracked:0,LodestoneDimension:"minecraft:the_end",LodestonePos:{X:-2, Y:114, Z:-67},display:{Name:'[{"text":"Armas:","italic":false,"color":"green","bold":true},{"text":" Levantar Dados","bold":false}]'}}