# Aplicação de Rank Rating
execute in minecraft:overworld run execute if score @p[distance=..8] rr matches 0 run team join rank_madeira @p[distance=..8]
execute in minecraft:overworld run execute if score @p[distance=..8] rr matches 1 run team join rank_pedra @p[distance=..8]
execute in minecraft:overworld run execute if score @p[distance=..8] rr matches 2 run team join rank_carvao @p[distance=..8]
execute in minecraft:overworld run execute if score @p[distance=..8] rr matches 3 run team join rank_cobre @p[distance=..8]
execute in minecraft:overworld run execute if score @p[distance=..8] rr matches 5 run team join rank_quartz @p[distance=..8]
execute in minecraft:overworld run execute if score @p[distance=..8] rr matches 4 run team join rank_ferro @p[distance=..8]
execute in minecraft:overworld run execute if score @p[distance=..8] rr matches 6 run team join rank_amethyst @p[distance=..8]
execute in minecraft:overworld run execute if score @p[distance=..8] rr matches 7 run team join rank_ouro @p[distance=..8]
execute in minecraft:overworld run execute if score @p[distance=..8] rr matches 8 run team join rank_redstone @p[distance=..8]
execute in minecraft:overworld run execute if score @p[distance=..8] rr matches 9 run team join rank_lazuli @p[distance=..8]
execute in minecraft:overworld run execute if score @p[distance=..8] rr matches 10 run team join rank_emerald @p[distance=..8]
execute in minecraft:overworld run execute if score @p[distance=..8] rr matches 11 run team join rank_diamond @p[distance=..8]
execute in minecraft:overworld run execute if score @p[distance=..8] rr matches 12 run team join rank_netherite @p[distance=..8]
execute in minecraft:overworld run execute if score @p[distance=..8] rr matches 13 run team join rank_drg @p[distance=..8]