execute store result score @a[limit=1] random run random roll 1..30
execute if score @p random matches 1 run function almondegas:task/skeld/admin/swipe_card
execute if score @p random matches 2 run function almondegas:task/skeld/cafeteria/clean_vent
execute if score @p random matches 3 run function almondegas:task/skeld/cafeteria/empty_garbage
execute if score @p random matches 4 run function almondegas:task/skeld/cafeteria/upload_data
execute if score @p random matches 5 run function almondegas:task/skeld/comms/divert_power
execute if score @p random matches 6 run function almondegas:task/skeld/comms/upload_data
execute if score @p random matches 7 run function almondegas:task/skeld/eletrical/calibrate_distributor
execute if score @p random matches 8 run function almondegas:task/skeld/eletrical/fix_wiring
execute if score @p random matches 9 run function almondegas:task/skeld/eletrical/upload_data
execute if score @p random matches 10 run function almondegas:task/skeld/engines/align_engine
execute if score @p random matches 11 run function almondegas:task/skeld/engines/divert_power_lower
execute if score @p random matches 12 run function almondegas:task/skeld/engines/divert_power_upper
execute if score @p random matches 13 run function almondegas:task/skeld/medbay/inspect_sample
execute if score @p random matches 14 run function almondegas:task/skeld/medbay/submit_scan
execute if score @p random matches 15 run function almondegas:task/skeld/navigation/chart_course
execute if score @p random matches 16 run function almondegas:task/skeld/navigation/divert_power
execute if score @p random matches 17 run function almondegas:task/skeld/navigation/stabilize_steering
execute if score @p random matches 18 run function almondegas:task/skeld/navigation/upload_data
execute if score @p random matches 19 run function almondegas:task/skeld/o2/clean_filer
execute if score @p random matches 20 run function almondegas:task/skeld/o2/divert_power
execute if score @p random matches 21 run function almondegas:task/skeld/o2/empty_chute
execute if score @p random matches 22 run function almondegas:task/skeld/reactor/start_reactor
execute if score @p random matches 23 run function almondegas:task/skeld/reactor/unlock_manifolds
execute if score @p random matches 24 run function almondegas:task/skeld/security/divert_power
execute if score @p random matches 25 run function almondegas:task/skeld/shields/divert_power
execute if score @p random matches 26 run function almondegas:task/skeld/shields/prime_shields
execute if score @p random matches 27 run function almondegas:task/skeld/storage/fuel_engines
execute if score @p random matches 28 run function almondegas:task/skeld/weapons/clear_asteroids
execute if score @p random matches 29 run function almondegas:task/skeld/weapons/divert_power
execute if score @p random matches 30 run function almondegas:task/skeld/weapons/upload_data