tag @p remove cor_vermelho
tag @p remove cor_laranja
tag @p remove cor_amarelo
tag @p remove cor_lima
tag @p remove cor_verde
tag @p remove cor_ciano
tag @p remove cor_teal
tag @p remove cor_azul
tag @p remove cor_roxo
tag @p remove cor_rosa
tag @p remove cor_branco
tag @p remove cor_cinza
tag @p remove cor_preto